version: '3.8'

services:
  api:
    image: bku-project-management-api
    environment:
      # host.docker.internal giúp container kết nối tới SQL Server cài trực tiếp trên VPS
      - ConnectionStrings__BKUConnection=Server=host.docker.internal;Database=BKU_SPMS_DB;User Id=sa;Password=Hanh@2205;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8080:8080"
    expose:
      - "8080"
    # Giúp container ánh xạ 'host.docker.internal' tới IP của VPS host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
