version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    expose:
      - "1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network
    restart: always

  api:
    image: bku-project-management-api
    environment:
      - ConnectionStrings__BKUConnection=Server=db;Database=BKU_SPMS_DB;User Id=sa;Password=Hanh@2205;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_HTTP_PORTS=8080
    # ports:
    #   - "8081:8080"
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
